import { createFileRoute, Link } from "@tanstack/react-router";
import { Shield, Lock, Database, Eye, Mail, FileText } from "lucide-react";

export const Route = createFileRoute("/trust")({
  head: () => ({
    meta: [
      { title: "Trust & Privacy — Mafia Mind" },
      {
        name: "description",
        content: "How Mafia Mind handles your account, gameplay data, AI processing, and privacy.",
      },
      { property: "og:title", content: "Trust & Privacy — Mafia Mind" },
      {
        property: "og:description",
        content: "Account, data, AI, and privacy practices for Mafia Mind.",
      },
    ],
  }),
  component: TrustPage,
});

function Section({
  icon: Icon,
  title,
  children,
}: {
  icon: typeof Shield;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="rounded-md border border-border/60 bg-card/40 p-6">
      <div className="flex items-center gap-3 mb-3">
        <div className="size-9 rounded-sm bg-primary/15 border border-primary/40 grid place-items-center">
          <Icon className="size-4 text-primary" />
        </div>
        <h2 className="font-serif text-xl text-foreground">{title}</h2>
      </div>
      <div className="text-sm text-muted-foreground leading-relaxed space-y-2">{children}</div>
    </section>
  );
}

function TrustPage() {
  return (
    <div className="relative min-h-screen px-6 sm:px-12 py-12">
      <div className="max-w-3xl mx-auto">
        <Link
          to="/"
          className="text-xs uppercase tracking-widest text-muted-foreground hover:text-primary"
        >
          ← Back to home
        </Link>
        <h1 className="font-serif text-4xl sm:text-5xl mt-4 mb-2 text-foreground">
          Trust &amp; Privacy
        </h1>
        <p className="text-sm text-muted-foreground mb-8">
          This page is maintained by the Mafia Mind team to answer common security and privacy
          questions about the game. It describes current practices and is not an independent
          certification or audit.
        </p>

        <div className="grid gap-4">
          <Section icon={Shield} title="Accounts &amp; authentication">
            <p>
              Sign-in is handled securely through Supabase Auth. Passwords are never stored in plain
              text. Sessions use short-lived JWTs that are refreshed automatically.
            </p>
          </Section>

          <Section icon={Database} title="What we store">
            <p>
              We store the minimum needed to run the game: your display name, the rooms you join,
              in-game chat messages, votes, and round-by-round suspicion scores generated by the AI.
              We do not sell or share this data.
            </p>
          </Section>

          <Section icon={Lock} title="Access controls">
            <p>
              Every database table uses row-level security. You can only read messages, votes, and
              scores from rooms you are a member of. Hidden role assignments are never returned to
              other players until the game ends.
            </p>
          </Section>

          <Section icon={Eye} title="AI processing">
            <p>
              AI players are powered by Google Gemini. Game chat from the current round is sent to
              the model so it can reply in character and rate suspicion. No account identifiers are
              sent — only display names and message text from the active room.
            </p>
          </Section>

          <Section icon={FileText} title="Data retention &amp; deletion">
            <p>
              Game data is retained for as long as the room exists. If you want your account and
              associated game history deleted, contact us using the address below and we will remove
              it.
            </p>
          </Section>

          <Section icon={Mail} title="Contact">
            <p>
              Security or privacy concerns? Reach out to the project owner through the GitHub
              repository linked in the README. We respond to reports in good faith and do not pursue
              researchers acting in good faith.
            </p>
          </Section>
        </div>

        <p className="text-xs text-muted-foreground/70 mt-8">
          Mafia Mind is an indie project. This page is editable content and may be updated as the
          game evolves.
        </p>
      </div>
    </div>
  );
}
